### ISSUE TITLE
Add Guilio and Nicole to makernexus org

### ISSUE THREAD

**Issue by Borgaard** [makernexus/nfcdoorz#1]
Greetings! Guilio and I would like to contribute to this org (not necessarily this nfcdoorz repo, as glorious as it is) with repos of mucho excellence, primarily website and Discourse related. Will y'all add us?

![please](https://media2.giphy.com/media/CT5Ye7uVJLFtu/giphy.gif)

**Comment by caesar2164** [comment]
yes please!
